# Generated by Django 5.2.12 on 2026-07-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Identifier of this record in the external registry, when source is external.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', help_text='Whether this record was created locally or imported from an external registry.', max_length=20),
        ),
    ]
