# Generated by Django 5.2.12 on 2026-08-17 12:48

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0007_alter_assetregistration_mv_registration_number'),
        ('common', '0008_typed_asset_registry'),
        ('companies', '0004_add_source_db_default'),
        ('individuals', '0004_add_source_db_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetregistration',
            name='chassis_number',
        ),
        migrations.RemoveField(
            model_name='assetregistration',
            name='engine_number',
        ),
        migrations.RemoveField(
            model_name='assetregistration',
            name='mv_registration_number',
        ),
        migrations.AlterField(
            model_name='assetregistration',
            name='location_address',
            field=models.TextField(blank=True, default='', help_text="Physical address where the asset is normally kept. For moveable assets, use the owner's address.", verbose_name='Location Address'),
        ),
        migrations.CreateModel(
            name='StandSaleTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('purchaser_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=20, verbose_name='Purchaser Type')),
                ('sale_date', models.DateField(verbose_name='Date of Sale')),
                ('terms', models.CharField(choices=[('cash', 'Cash'), ('installments', 'Installments')], max_length=20, verbose_name='Terms')),
                ('valuation_type', models.CharField(choices=[('purchase_price', 'Purchase Price'), ('estimated_value', 'Estimated Value'), ('professional_valuation', 'Professional Valuation')], max_length=30, verbose_name='Valuation Type')),
                ('title_status', models.CharField(choices=[('deeds', 'Deeds'), ('purchase_agreement', 'Purchase Agreement')], max_length=30, verbose_name='Title Status')),
                ('value_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Value Amount')),
                ('is_completed', models.BooleanField(db_index=True, default=False, help_text='Set when ownership change finalises the sale.', verbose_name='Completed')),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_transitions', to='asset_management.assetregistration', verbose_name='Asset')),
                ('company_purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stand_purchases', to='companies.companybranch', verbose_name='Company Purchaser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.currency', verbose_name='Currency')),
                ('individual_purchaser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stand_purchases', to='individuals.individual', verbose_name='Individual Purchaser')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stand Sale Transition',
                'verbose_name_plural': 'Stand Sale Transitions',
                'ordering': ['-sale_date', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='AssetOwnershipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('event_type', models.CharField(choices=[('ownership_change', 'Ownership Change'), ('sale_transition', 'Sale Transition')], db_index=True, max_length=30, verbose_name='Event Type')),
                ('previous_owner_type', models.CharField(blank=True, max_length=20)),
                ('new_owner_type', models.CharField(blank=True, max_length=20)),
                ('valuation_type', models.CharField(blank=True, choices=[('purchase_price', 'Purchase Price'), ('estimated_value', 'Estimated Value'), ('professional_valuation', 'Professional Valuation')], max_length=30)),
                ('title_status', models.CharField(blank=True, choices=[('deeds', 'Deeds'), ('purchase_agreement', 'Purchase Agreement')], max_length=30)),
                ('terms', models.CharField(blank=True, choices=[('cash', 'Cash'), ('installments', 'Installments')], max_length=20)),
                ('value_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_events', to='asset_management.assetregistration', verbose_name='Asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('new_company_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.companybranch')),
                ('new_individual_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='individuals.individual')),
                ('previous_company_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.companybranch')),
                ('previous_individual_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='individuals.individual')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('sale_transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_events', to='asset_management.standsaletransition')),
            ],
            options={
                'verbose_name': 'Asset Ownership Event',
                'verbose_name_plural': 'Asset Ownership Events',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('mv_registration_number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='MV Registration Number')),
                ('chassis_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Chassis Number')),
                ('engine_number', models.CharField(blank=True, max_length=100, verbose_name='Engine Number')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='asset_management.assetregistration', verbose_name='Asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Details',
                'verbose_name_plural': 'Vehicle Details',
            },
        ),
        migrations.CreateModel(
            name='LandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('stand_address', models.CharField(blank=True, max_length=255, verbose_name='Stand Address')),
                ('stand_number', models.CharField(db_index=True, max_length=50, verbose_name='Stand Number')),
                ('stand_size', models.CharField(blank=True, help_text='Numeric size, e.g. 1200', max_length=50, verbose_name='Stand Size')),
                ('stand_size_unit', models.CharField(default='sq_m', max_length=10, verbose_name='Stand Size Unit')),
                ('valuation_type', models.CharField(choices=[('purchase_price', 'Purchase Price'), ('estimated_value', 'Estimated Value'), ('professional_valuation', 'Professional Valuation')], max_length=30, verbose_name='Valuation Type')),
                ('title_status', models.CharField(choices=[('deeds', 'Deeds'), ('purchase_agreement', 'Purchase Agreement')], max_length=30, verbose_name='Title Status')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land', to='asset_management.assetregistration', verbose_name='Asset')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='land_assets', to='common.city', verbose_name='City/Town')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='land_assets', to='common.suburb', verbose_name='Suburb/Area/Development')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Land Details',
                'verbose_name_plural': 'Land Details',
                'constraints': [models.UniqueConstraint(models.F('city'), models.F('suburb'), django.db.models.functions.text.Lower('stand_number'), name='ar_uq_land_city_suburb_stand_ci')],
            },
        ),
        migrations.CreateModel(
            name='MobileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('imei', models.CharField(db_index=True, max_length=20, verbose_name='IMEI')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='asset_management.assetregistration', verbose_name='Asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mobile Details',
                'verbose_name_plural': 'Mobile Details',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('imei'), name='ar_uq_mobile_imei_ci')],
            },
        ),
        migrations.AddConstraint(
            model_name='standsaletransition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_completed', False)), fields=('asset',), name='ar_uq_open_sale_per_asset'),
        ),
        migrations.AddConstraint(
            model_name='vehicledetails',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('mv_registration_number'), condition=models.Q(('mv_registration_number', ''), _negated=True), name='ar_uq_vehicle_mv_reg_ci'),
        ),
        migrations.AddConstraint(
            model_name='vehicledetails',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('chassis_number'), condition=models.Q(('chassis_number', ''), _negated=True), name='ar_uq_vehicle_chassis_ci'),
        ),
        migrations.AddConstraint(
            model_name='vehicledetails',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('engine_number'), condition=models.Q(('engine_number', ''), _negated=True), name='ar_uq_vehicle_engine_ci'),
        ),
    ]
