# Generated by Django 5.2.12 on 2026-09-09 12:00

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management', '0008_remove_assetregistration_chassis_number_and_more'),
        ('common', '0009_reseed_land_lookups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='landdetails',
            name='stand_address',
            field=models.CharField(max_length=255, verbose_name='Stand Address'),
        ),
        migrations.AddConstraint(
            model_name='landdetails',
            constraint=models.UniqueConstraint(models.F('suburb'), django.db.models.functions.text.Lower('stand_address'), name='ar_uq_land_suburb_address_ci'),
        ),
    ]
