# Generated by Django 5.2.12 on 2026-08-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_seed_collateral_asset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupoption',
            name='category',
            field=models.CharField(choices=[('PartyType', 'Party Type'), ('BaseAssetType', 'Base Asset Type'), ('AssetCondition', 'Asset Condition'), ('CollateralAssetCategory', 'Collateral Asset Category'), ('Industry', 'Industry')], db_index=True, max_length=50),
        ),
    ]
