# Generated by Django 5.2.12 on 2026-08-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_lookupoption_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('id', 'Identification'), ('proof_of_address', 'Proof of Address'), ('contract', 'Contract'), ('title_deed', 'Title Deed'), ('purchase_agreement', 'Purchase Agreement'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lookupoption',
            name='category',
            field=models.CharField(choices=[('PartyType', 'Party Type'), ('BaseAssetType', 'Base Asset Type'), ('AssetCondition', 'Asset Condition'), ('CollateralAssetCategory', 'Collateral Asset Category'), ('Industry', 'Industry'), ('ValuationType', 'Valuation Type'), ('TitleStatus', 'Title Status'), ('SaleTerms', 'Sale Terms')], db_index=True, max_length=50),
        ),
    ]
