# Generated by Django 5.2.12 on 2026-07-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0003_add_party_source_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], db_default='internal', default='internal', help_text='Whether this record was created locally or imported from an external registry.', max_length=20),
        ),
    ]
